/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author big_a
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        transparencia_boton();
        this.setLocationRelativeTo(null);

        btn_inicio.setBackground(new java.awt.Color(0,0,0,1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo_cerrar = new javax.swing.JLabel();
        logo_informacion = new javax.swing.JLabel();
        logo_eliminar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logo_registrar = new javax.swing.JLabel();
        logo_inicio = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JButton();
        btn_registro = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_informacion = new javax.swing.JButton();
        btn_reportes = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Vector.png"))); // NOI18N
        panel_menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        logo_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/power-off-button 1.png"))); // NOI18N
        panel_menu.add(logo_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        logo_informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/dashboard-monitoring 1.png"))); // NOI18N
        panel_menu.add(logo_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        logo_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/advice 1.png"))); // NOI18N
        panel_menu.add(logo_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/chat-question 1.png"))); // NOI18N
        panel_menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        logo_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/team 1.png"))); // NOI18N
        panel_menu.add(logo_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 30));

        logo_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/home-button 1.png"))); // NOI18N
        panel_menu.add(logo_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Inicio.png"))); // NOI18N
        btn_inicio.setBorder(null);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        panel_menu.add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, 30));

        btn_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Registrar.png"))); // NOI18N
        btn_registro.setBorder(null);
        panel_menu.add(btn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 30));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Eliminar.png"))); // NOI18N
        panel_menu.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 100, -1));

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Modificar.png"))); // NOI18N
        panel_menu.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 110, 30));

        btn_informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Informacion.png"))); // NOI18N
        panel_menu.add(btn_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 140, 30));

        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Reportes.png"))); // NOI18N
        panel_menu.add(btn_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 100, 30));

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Cerrar Sesion.png"))); // NOI18N
        panel_menu.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 150, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/Rectangle 1.png"))); // NOI18N
        panel_menu.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_inicioActionPerformed

    public void transparencia_boton(){
        btn_inicio.setOpaque(false);
        btn_inicio.setContentAreaFilled(false);
        btn_inicio.setBorderPainted(false);
        
        btn_registro.setOpaque(false);
        btn_registro.setContentAreaFilled(false);
        btn_registro.setBorderPainted(false);
        
        btn_eliminar.setOpaque(false);
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setBorderPainted(false);
        
        btn_modificar.setOpaque(false);
        btn_modificar.setContentAreaFilled(false);
        btn_modificar.setBorderPainted(false);
        
        btn_informacion.setOpaque(false);
        btn_informacion.setContentAreaFilled(false);
        btn_informacion.setBorderPainted(false);
        
        btn_reportes.setOpaque(false);
        btn_reportes.setContentAreaFilled(false);
        btn_reportes.setBorderPainted(false);
        
        btn_cerrar.setOpaque(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setBorderPainted(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_informacion;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo_cerrar;
    private javax.swing.JLabel logo_eliminar;
    private javax.swing.JLabel logo_informacion;
    private javax.swing.JLabel logo_inicio;
    private javax.swing.JLabel logo_registrar;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
