/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author big_a
 */
public final class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
       transparencia_todo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boton_login = new javax.swing.JButton();
        boton_olvidaste = new javax.swing.JButton();
        txt_contraseña = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        boton_contraseña = new javax.swing.JLabel();
        boton_usuario = new javax.swing.JLabel();
        iniciar = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        texto_iniciar_sesion = new javax.swing.JLabel();
        linea = new javax.swing.JLabel();
        card = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Iniciar Sesion");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, -1, -1));

        boton_login.setBackground(new java.awt.Color(255, 255, 255));
        boton_login.setForeground(new java.awt.Color(255, 255, 255));
        boton_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/login.png"))); // NOI18N
        boton_login.setBorder(null);
        boton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_loginActionPerformed(evt);
            }
        });
        jPanel2.add(boton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 489, 410, 50));

        boton_olvidaste.setBackground(new java.awt.Color(255, 255, 255));
        boton_olvidaste.setForeground(new java.awt.Color(255, 255, 255));
        boton_olvidaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/¿Olvidaste tu contraseña_.png"))); // NOI18N
        boton_olvidaste.setBorder(null);
        jPanel2.add(boton_olvidaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 440, 160, 20));

        txt_contraseña.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        txt_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_contraseña.setBorder(null);
        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 410, 50));

        txt_usuario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setBorder(null);
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 410, 50));

        contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/Ingresar Contraseña.png"))); // NOI18N
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        boton_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/boton.png"))); // NOI18N
        boton_contraseña.setText("jLabel2");
        jPanel2.add(boton_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 420, -1));

        boton_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/boton.png"))); // NOI18N
        boton_usuario.setText("jLabel2");
        jPanel2.add(boton_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 420, -1));

        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/Ingresar Usuario.png"))); // NOI18N
        jPanel2.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, -1, -1));

        texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/Sistema Ruta Scan.png"))); // NOI18N
        jPanel2.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 190, 30));

        texto_iniciar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/Iniciar Sesión.png"))); // NOI18N
        jPanel2.add(texto_iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/Line 1_1.png"))); // NOI18N
        jPanel2.add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 200, -1));

        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/card.png"))); // NOI18N
        card.setText("Registro de usuarios moviScan");
        jPanel2.add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 480, 550));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/image 1.png"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 630));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txt_usuarioActionPerformed
public void transparencia_todo(){
        boton_olvidaste.setOpaque(false);
        boton_olvidaste.setContentAreaFilled(false);
        boton_olvidaste.setBorderPainted(false);
        
       txt_usuario.setBackground(new java.awt.Color(0,0,0,1));
        txt_contraseña.setBackground(new java.awt.Color(0,0,0,1));
        boton_login.setBackground(new java.awt.Color(0,0,0,1));
        boton_olvidaste.setBackground(new java.awt.Color(0,0,0,1));
    }
    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaActionPerformed

    private void boton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boton_contraseña;
    private javax.swing.JButton boton_login;
    private javax.swing.JButton boton_olvidaste;
    private javax.swing.JLabel boton_usuario;
    private javax.swing.JLabel card;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel linea;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto_iniciar_sesion;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
